= React für Anfänger
:project-name: react-session
:todos-url: https://jsonplaceholder.typicode.com/todos
:source-highlighter: rouge
:source-language: typescript

== Vorbedingungen

.Abhängigkeiten
* NodeJS
* IDE?

== Erste Schritte

=== Projekt aufsetzen

.SkelettProjekt erzeugen
[subs="attributes+"]
npx create-react-app {project-name} --template typescript

.Devserver starten
[subs="attributes+"]
cd {project-name}
npm start

=== Warum Create React App?

.+:
* Schnelles Scaffolding
* Build-Script included
* dev-server, linter, test-runner... included

.-
* Customizing schwierig ohne 'eject' (z.B. webpack config, ...)
* Nur Single Page Application

=== Projekt Struktur

==== Top Level Files

gitignore::
Für git ignores... :)

package.json::
Informationen über das Projekt.
Hier werden Dependencies deklariert und scripts (z.B. start, build) definiert.

package-lock.json::
Lockfile für Dependencies

README.md::
Ein readme file...

tsconfig.json::
Konfiguration für den typescript compiler (tsc)

==== public

Beinhaltet statische Assets.

[IMPORTANT]
Hier liegt auch die ausgelieferte index.html.

==== src

Source Code für die Anwendung.
Beinhaltet Javascript und dynamische Ressourcen.

index.tsx::
Entry-point von CRA-Apps.
Hier wird die App per `ReeactDOM.createRoot(...)` ins DOM eingehängt (bzw. `ReactDOM.render(...)` in React < 18).

App.*::
Gehören zur `App.tsx` Komponente.
Der Gedanke bei Komponenten ist, zusammengehörigen Code in einer wiederverwendbaren Weise zu bündeln.
Gerne mal mit `App.tsx` spielen oder auch 2x einbinden.

setupTests.ts::
Setup File für Test Runner.

== Hands On

Wir bauen eine ToDo-App :).
Dazu erstmal `src` etwas aufräumen.

.Kann weg:
* App.css
* App.test.tsx
* logo.svg

Und App.tsx leeren:

----
export default function App() {
  return <></>;
}
----

Optional: Code Formatter installieren und einrichten.

 npm i prettier

=== Todo Liste

Wir wollen schnell etwas halbwegs Schönes erstellen.
Deshalb nutzen wir eine Komponentenbibliothek.
Wir benutzen hier material-ui (https://mui.com/)

  npm install @mui/material @emotion/react @emotion/styled

Komponente `src/todos/TodoList.tsx` erstellen.
Zuerst ein Dummy für die Listenkomponente selbst:

----
export default function TodoList() {
  return <></>;
}
----

und in App.tsx anziehen:

----
import TodoList from "./todos/TodoList";

export default function App() {
  return <TodoList />;
}
----

Dev Server sollte jetzt immer noch weißes Bild zeigen.
TodoList rendert ein React.Fragment und damit nichts.

Wir definieren ein dummy Todo:

----
const todo = {
  id: 1,
  title: "Wichtige Dinge tun",
  completed: true,
};
----

und zeigen etwas in der Liste an:

----
export default function TodoList() {
  return (
    <List>
      <ListItem>
        <ListItemText primary={todo.title} />
      </ListItem>
    </List>
  );
}
----

Fehlt noch eine Anzeige für `todo.completed`:

----
export default function TodoList() {
  return (
    <List>
      <ListItem secondaryAction={<Checkbox checked={todo.completed} />}>
        <ListItemText primary={todo.title} />
      </ListItem>
    </List>
  );
}
----

=== Mapping über Datenliste

Bisher geht nur 1 Todo, nicht wirklich hilfreich.
Daher als nächstes mehrere todos:

----
import React from "react";
import Todo from "./Todo";

interface TodoListProps {
  todos: Todo[];
}

export default function TodoList({ todos }: TodoListProps) {
  return <div></div>;
}
----

und in App.tsx:

.App.tsx
----
import Todo from "./todos/Todo";
import TodoList from "./todos/TodoList";

const todos: Todo[] = [
  {
    id: 1,
    title: "Wichtige Dinge tun",
    completed: false,
  },
  {
    id: 2,
    title: "Lustige Dinge tun",
    completed: true,
  },
];

export default function App() {
  return <TodoList todos={todos} />;
}
----

TodoList ausgestalten:

.TodoList.tsx
----
export default function TodoList({ todos }: TodoListProps) {
  return (
    <div>
      <div>Todos</div>
      {todos.map((todo) => (
        <TodoItem key={todo.id} todo={todo} />
      ))}
    </div>
  );
}
----

`key` Property ist bei Mapping von Komponenten über Listen notwendig (siehe warning in console).
Anhand von `key` kann React die verschiedenen Komponenten unterscheiden und entscheiden, welche bei Bedarf neu gerendert werden müssen.

=== children prop

Komponente für "schönen" Rahmen um beliebige Komponente.

.BorderedBox.tsx
----
import React, { CSSProperties, ReactNode } from "react";

const borderedBoxStyle: CSSProperties = {
  border: "solid black 5px",
  borderRadius: "5px",
};

interface BorderedBoxProps {
  children: ReactNode;
}

export default function BorderedBox({ children }: BorderedBoxProps) {
  return <div style={borderedBoxStyle}>{children}</div>;
}
----

`children` ist eine besondere prop in dem Sinne, dass sie nicht "als Attribut" gesetzt werden muss, sondern auch durch den Content zwischen öffnendem und schließendem Tag befüllt werden kann.

Einfügen in TodoList:

.TodoList.tsx
----
export default function TodoList({ todos }: TodoListProps) {
  return (
    <div>
      <div>Todos</div>
      <BorderedBox>
        {todos.map((todo) => (
          <TodoItem key={todo.id} todo={todo} />
        ))}
      </BorderedBox>
    </div>
  );
}
----

=== Hooks

Bisher keine Interaktivität.
Wir wollen, dass klick auf checkbox den die Aufgabe als abgeschlossen markiert.
Die App braucht sowas wie einen Zustand.

==== useState

Hinzufügen von State zu `App.tsx`

.App.tsx
----
import Todo from "./todos/Todo";
import TodoList from "./todos/TodoList";
import { useState } from "react";

const initialTodos: Todo[] = [
  {
    id: 1,
    title: "Wichtige Dinge tun",
    completed: false,
  },
  {
    id: 2,
    title: "Lustige Dinge tun",
    completed: true,
  },
];

export default function App() {
  const [todos, setTodos] = useState(initialTodos);

  return <TodoList todos={todos} />;
}
----

Eventhandler an den Komponenten hinzufügen

.App.tsx
----
export default function App() {
  const [todos, setTodos] = useState(initialTodos);

  const handleTodoCompletedClicked = (id: Todo["id"]) =>
    setTodos(
      todos.map((todo) =>
        todo.id === id
          ? {
            ...todo,
            completed: !todo.completed,
          }
          : todo
      )
    );

  return (
    <TodoList
      todos={todos}
      onTodoCompletedClicked={handleTodoCompletedClicked}
    />
  );
}
----

.TodoList.tsx
----
interface TodoListProps {
  todos: Todo[];
  onTodoCompletedClicked: (todoId: Todo["id"]) => unknown;
}

export default function TodoList({
  todos,
  onTodoCompletedClicked,
}: TodoListProps) {
  return (
    <div>
      <div>Todos</div>
      <BorderedBox>
        {todos.map((todo) => (
          <TodoItem
            key={todo.id}
            todo={todo}
            onCheckboxClick={() => onTodoCompletedClicked(todo.id)}
          />
        ))}
      </BorderedBox>
    </div>
  );
}
----

.TodoItem.tsx
----
interface TodoItemProps {
  todo: Todo;
  onCheckboxClick: () => unknown;
}

export default function TodoItem({ todo, onCheckboxClick }: TodoItemProps) {
  return (
    <div>
      <input
        type={"checkbox"}
        checked={todo.completed}
        onClick={onCheckboxClick}
      />
      <span>{todo.title}</span>
    </div>
  );
}
----
