= React für Anfänger
:project-name: react-session
:todos-url: https://jsonplaceholder.typicode.com/todos
:source-highlighter: rouge
:source-language: typescript

== Vorbedingungen

.Abhängigkeiten
* NodeJS
* IDE?

== Erste Schritte

=== Projekt aufsetzen

.SkelettProjekt erzeugen
[subs="attributes+"]
npx create-react-app {project-name} --template typescript

.Devserver starten
[subs="attributes+"]
cd {project-name}
npm start

=== Warum Create React App?

.+:
* Schnelles Scaffolding
* Build-Script included
* dev-server, linter, test-runner... included

.-
* Customizing schwierig ohne 'eject' (z.B. webpack config, ...)
* Nur Single Page Application

=== Projekt Struktur

==== Top Level Files

gitignore::
Für git ignores... :)

package.json::
Informationen über das Projekt.
Hier werden Dependencies deklariert und scripts (z.B. start, build) definiert.

package-lock.json::
Lockfile für Dependencies

README.md::
Ein readme file...

tsconfig.json::
Konfiguration für den typescript compiler (tsc)

==== public

Beinhaltet statische Assets.

[IMPORTANT]
Hier liegt auch die ausgelieferte index.html.

==== src

Source Code für die Anwendung.
Beinhaltet Javascript und dynamische Ressourcen.

index.tsx::
Entry-point von CRA-Apps.
Hier wird die App per `ReeactDOM.createRoot(...)` ins DOM eingehängt (bzw. `ReactDOM.render(...)` in React < 18).

App.*::
Gehören zur `App.tsx` Komponente.
Der Gedanke bei Komponenten ist, zusammengehörigen Code in einer wiederverwendbaren Weise zu bündeln.
Gerne mal mit `App.tsx` spielen oder auch 2x einbinden.

setupTests.ts::
Setup File für Test Runner.

== Hands On

Wir bauen eine ToDo-App :).
Dazu erstmal `src` etwas aufräumen.

.Kann weg:
* App.css
* App.test.tsx
* logo.svg

Und App.tsx leeren:

----
export default function App() {
  return <></>;
}
----

Optional: Code Formatter installieren und einrichten.

 npm i prettier

=== Todo

Interface `src/todos/Todo.ts` definieren:

----
export default interface Todo {
  id: number;
  title: string;
  completed: boolean;
}
----

Komponente `src/todos/TodoItem.tsx` definieren:

----
import Todo from "./Todo";

interface TodoItemProps {
  todo: Todo;
}

export default function TodoItem({ todo }: TodoItemProps) {
  return <></>;
}
----

und in App.tsx anziehen:

----
import Todo from "./todos/Todo";
import TodoItem from "./todos/TodoItem";

const todo: Todo = {
  id: 1,
  title: "Wichtige Dinge tun",
  completed: false,
};

export default function App() {
  return <TodoItem todo={todo} />;
}
----

Dev Server sollte jetzt immer noch weißes Bild zeigen.
Noch rendert `TodoItem` nichts.

Etwas hübschere Variante (ohne Respekt für a11y oder html Semantik)

----
import Todo from "./Todo";
import { CSSProperties } from "react";

const containerStyle: CSSProperties = {
  display: "flex",
  flexDirection: "row",
};

interface TodoItemProps {
  todo: Todo;
}

export default function TodoItem({ todo }: TodoItemProps) {
  return (
    <div style={containerStyle}>
      <input type={"checkbox"} checked={todo.completed} />
      <div>{todo.title}</div>
    </div>
  );
}
----
