= React für Anfänger
:project-name: react-session
:todos-url: https://jsonplaceholder.typicode.com/todos
:source-highlighter: rouge
:source-language: typescript

== Vorbedingungen

.Abhängigkeiten
* NodeJS
* IDE?

== Erste Schritte

=== Projekt aufsetzen

.SkelettProjekt erzeugen
[subs="attributes+"]
npx create-react-app {project-name} --template typescript

.Devserver starten
[subs="attributes+"]
cd {project-name}
npm start

=== Warum Create React App?

.+:
* Schnelles Scaffolding
* Build-Script included
* dev-server, linter, test-runner... included

.-
* Customizing schwierig ohne 'eject' (z.B. webpack config, ...)
* Nur Single Page Application

=== Projekt Struktur

==== Top Level Files

gitignore::
Für git ignores... :)

package.json::
Informationen über das Projekt.
Hier werden Dependencies deklariert und scripts (z.B. start, build) definiert.

package-lock.json::
Lockfile für Dependencies

README.md::
Ein readme file...

tsconfig.json::
Konfiguration für den typescript compiler (tsc)

==== public

Beinhaltet statische Assets.

[IMPORTANT]
Hier liegt auch die ausgelieferte index.html.

==== src

Source Code für die Anwendung.
Beinhaltet Javascript und dynamische Ressourcen.

index.tsx::
Entry-point von CRA-Apps.
Hier wird die App per `ReeactDOM.createRoot(...)` ins DOM eingehängt (bzw. `ReactDOM.render(...)` in React < 18).

App.*::
Gehören zur `App.tsx` Komponente.
Der Gedanke bei Komponenten ist, zusammengehörigen Code in einer wiederverwendbaren Weise zu bündeln.
Gerne mal mit `App.tsx` spielen oder auch 2x einbinden.

setupTests.ts::
Setup File für Test Runner.

== Hands On

Wir bauen eine ToDo-App :).
Dazu erstmal `src` etwas aufräumen.

.Kann weg:
* App.css
* App.test.tsx
* logo.svg

Und App.tsx leeren:

----
export default function App() {
  return <></>;
}
----

Dev Server sollte jetzt immer noch weißes Bild zeigen.
App rendert ein React.Fragment und damit nichts.

Optional: Code Formatter installieren und einrichten.

 npm i prettier

=== Todo Liste

Wir wollen schnell etwas halbwegs Schönes erstellen.
Deshalb nutzen wir eine Komponentenbibliothek.
Wir benutzen hier material-ui (https://mui.com/)

  npm install @mui/material @emotion/react @emotion/styled @mui/icons-material

Wir definieren ein dummy Todo:

----
const todo = {
  id: 1,
  title: "Wichtige Dinge tun",
  completed: true,
};
----

und zeigen etwas in der Liste an:

----
export default function App() {
  return (
    <List>
      <ListItem>
        <ListItemText primary={todo.title} />
      </ListItem>
    </List>
  );
}
----

Fehlt noch eine Anzeige für `todo.completed`:

----
export default function App() {
  return (
    <List>
      <ListItem secondaryAction={<Checkbox checked={todo.completed} />}>
        <ListItemText primary={todo.title} />
      </ListItem>
    </List>
  );
}
----

=== Mapping über Datenliste

Bisher geht nur 1 Todo, nicht wirklich hilfreich.
Daher als nächstes mehrere todos:

----
const todos = [
  {
    id: 1,
    title: "Wichtige Dinge tun",
    completed: true,
  },
  {
    id: 2,
    title: "Lustige Dinge tun",
    completed: false,
  },
];
----

und TodoList anpassen:

----
export default function App() {
  return (
    <List>
      {todos.map((todo) => (
        <ListItem
          key={todo.id}
          secondaryAction={<Checkbox checked={todo.completed} />}
        >
          <ListItemText primary={todo.title} />
        </ListItem>
      ))}
    </List>
  );
}
----

`key` Property ist bei Mapping von Komponenten über Listen notwendig (siehe warning in console).
Anhand von `key` kann React die verschiedenen Komponenten unterscheiden und entscheiden, welche bei Bedarf neu gerendert werden müssen (see https://reactjs.org/docs/lists-and-keys.html).

=== Hooks

Bisher keine Interaktivität.
Wir wollen Todos selbst hinzufügen.
Wir wollen, dass klick auf checkbox den die Aufgabe als abgeschlossen markiert.
Die Liste braucht Zustand.

==== useState

===== Add Todo

Hinzufügen von State zu `TodoList.tsx`

----
import React, { useState } from "react";
import { Checkbox, List, ListItem, ListItemText } from "@mui/material";

const initialTodos = [
  {
    id: 1,
    title: "Wichtige Dinge tun",
    completed: true,
  },
  {
    id: 2,
    title: "Lustige Dinge tun",
    completed: false,
  },
];

export default function App() {
  const [todos, setTodos] = useState(initialTodos);

  return (
    <List>
      {todos.map((todo) => (
        <ListItem
          key={todo.id}
          secondaryAction={<Checkbox checked={todo.completed} />}
        >
          <ListItemText primary={todo.title} />
        </ListItem>
      ))}
    </List>
  );
}
----

===== Toggle Completed

Wir brauchen einen Eventhandler:

----
  const handleChange = (index: number) => () => {
    const newTodos = [...todos];
    const changedTodo = newTodos[index];
    changedTodo.completed = !changedTodo.completed;
    setTodos(newTodos);
  };
----

----
            <Checkbox checked={todo.completed} onChange={handleChange(index)} />
----

==== useEffect

Aktuell sind Todos hart codiert.
Was, wenn wir die Todos von beim rendern der Liste von einem Backend laden wollen?
Mithilfe des `useEffect()` Hooks kann das als Seiteneffekt des Renderns der Komponente ausgedrückt werden.

Zunächst Definition von fetch Funktion:

----
async function fetchTodos() {
  const response = await fetch("https://jsonplaceholder.typicode.com/todos");
  if (response.ok) {
    return response.json();
  }
  throw Error("response not ok");
}
----

Und als Seiteneffekt einbinden:

----
  useEffect(() => {
    fetchTodos()
      .then(setTodos)
      .catch((e) => console.log(e));
  });
----

Jetzt sollten beim Rendern der Komponente die Todos vom Backend geladen werden.

Wir haben allerdings einen kritischen Bug eingebaut, der gut im Netzwerk Tab der Browser Devtools einsehbar ist.
`useEffect` wird bei jedem Rerender neu getriggert.
Da unser Effekt jedes mal `setTodos` aufruft und damit ein Rerender triggert, hängen wir in einer Endlosschleife aus Fetch und Rerender.

Quickfix mit Dependency Array:

----
  useEffect(() => {
    fetchTodos()
      .then(setTodos)
      .catch((e) => console.log(e));
  }, []);
----

NOTE: Mit `React.StrictMode` werden Effekte im dev-Mode trotzdem 2x ausgeführt (see https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects).

Richtiger Fix: In der Logik anpassen, dass nur geladen werden muss, wenn noch keine Daten vorliegen.
Z.B. initiale `todos` auf undefined und Daten werden nur geladen, wenn `todos` nicht undefined sind.

----
  const [todos, setTodos] = useState();

  useEffect(() => {
    if (todos === undefined) {
      fetchTodos()
        .then(setTodos)
        .catch((e) => console.log(e));
    }
  }, [todos]);
----

Es sollten nun Typescript Fehler entstehen, da der Typ von `todos` nicht mehr inferiert werden kann.
Daher ist eine Definition von Todo nötig:

----
interface Todo {
  id: number;
  title: string;
  completed: boolean;
}
----

und Einsetzen in die entsprechenden Stellen im Code:

----
async function fetchTodos(): Promise<Todo[]> {...}
...
  const [todos, setTodos] = useState<Todo[]>();
----

Da `todos` jetzt `undefined` sein kann, treten weitere Typescript Fehler auf.
Am einfachsten ist Abfangen über early return:

----
  if (todos === undefined) {
    return <CircularProgress />;
  }
----
