= React für Anfänger
:project-name: react-session
:todos-url: https://jsonplaceholder.typicode.com/todos
:source-highlighter: rouge
:source-language: typescript

== Vorbedingungen

.Abhängigkeiten
* NodeJS
* IDE?

== Erste Schritte

=== Projekt aufsetzen

.SkelettProjekt erzeugen
[subs="attributes+"]
npx create-react-app {project-name} --template typescript

.Devserver starten
[subs="attributes+"]
cd {project-name}
npm start

=== Warum Create React App?

.+:
* Schnelles Scaffolding
* Build-Script included
* dev-server, linter, test-runner... included

.-
* Customizing schwierig ohne 'eject' (z.B. webpack config, ...)
* Nur Single Page Application

=== Projekt Struktur

==== Top Level Files

gitignore::
Für git ignores... :)

package.json::
Informationen über das Projekt.
Hier werden Dependencies deklariert und scripts (z.B. start, build) definiert.

package-lock.json::
Lockfile für Dependencies

README.md::
Ein readme file...

tsconfig.json::
Konfiguration für den typescript compiler (tsc)

==== public

Beinhaltet statische Assets.

[IMPORTANT]
Hier liegt auch die ausgelieferte index.html.

==== src

Source Code für die Anwendung.
Beinhaltet Javascript und dynamische Ressourcen.

index.tsx::
Entry-point von CRA-Apps.
Hier wird die App per `ReeactDOM.createRoot(...)` ins DOM eingehängt (bzw. `ReactDOM.render(...)` in React < 18).

App.*::
Gehören zur `App.tsx` Komponente.
Der Gedanke bei Komponenten ist, zusammengehörigen Code in einer wiederverwendbaren Weise zu bündeln.
Gerne mal mit `App.tsx` spielen oder auch 2x einbinden.

setupTests.ts::
Setup File für Test Runner.

== Hands On

Wir bauen eine ToDo-App :).
Dazu erstmal `src` etwas aufräumen.

.Kann weg:
* App.css
* App.test.tsx
* logo.svg

Und App.tsx leeren:

----
export default function App() {
  return <></>;
}
----

Optional: Code Formatter installieren und einrichten.

 npm i prettier

=== Todo Liste

Wir wollen schnell etwas halbwegs Schönes erstellen.
Deshalb nutzen wir eine Komponentenbibliothek.
Wir benutzen hier material-ui (https://mui.com/)

  npm install @mui/material @emotion/react @emotion/styled

Komponente `src/todos/TodoList.tsx` erstellen.
Zuerst ein Dummy für die Listenkomponente selbst:

----
export default function TodoList() {
  return <></>;
}
----

und in App.tsx anziehen:

----
import TodoList from "./todos/TodoList";

export default function App() {
  return <TodoList />;
}
----

Dev Server sollte jetzt immer noch weißes Bild zeigen.
TodoList rendert ein React.Fragment und damit nichts.

Wir definieren ein dummy Todo:

----
const todo = {
  id: 1,
  title: "Wichtige Dinge tun",
  completed: true,
};
----

und zeigen etwas in der Liste an:

----
export default function TodoList() {
  return (
    <List>
      <ListItem>
        <ListItemText primary={todo.title} />
      </ListItem>
    </List>
  );
}
----

Fehlt noch eine Anzeige für `todo.completed`:

----
export default function TodoList() {
  return (
    <List>
      <ListItem secondaryAction={<Checkbox checked={todo.completed} />}>
        <ListItemText primary={todo.title} />
      </ListItem>
    </List>
  );
}
----

=== Mapping über Datenliste

Bisher geht nur 1 Todo, nicht wirklich hilfreich.
Daher als nächstes mehrere todos:

----
const todos = [
  {
    id: 1,
    title: "Wichtige Dinge tun",
    completed: true,
  },
  {
    id: 2,
    title: "Lustige Dinge tun",
    completed: false,
  },
];
----

und TodoList anpassen:

----
export default function TodoList() {
  return (
    <List>
      {todos.map((todo) => (
        <ListItem
          key={todo.id}
          secondaryAction={<Checkbox checked={todo.completed} />}
        >
          <ListItemText primary={todo.title} />
        </ListItem>
      ))}
    </List>
  );
}
----

`key` Property ist bei Mapping von Komponenten über Listen notwendig (siehe warning in console).
Anhand von `key` kann React die verschiedenen Komponenten unterscheiden und entscheiden, welche bei Bedarf neu gerendert werden müssen (see https://reactjs.org/docs/lists-and-keys.html).

=== Hooks

Bisher keine Interaktivität.
Wir wollen, dass klick auf checkbox den die Aufgabe als abgeschlossen markiert.
Die Liste braucht Zustand.

==== useState

Hinzufügen von State zu `TodoList.tsx`

----
import React, { useState } from "react";
import { Checkbox, List, ListItem, ListItemText } from "@mui/material";

const initialTodos = [
  {
    id: 1,
    title: "Wichtige Dinge tun",
    completed: true,
  },
  {
    id: 2,
    title: "Lustige Dinge tun",
    completed: false,
  },
];

export default function TodoList() {
  const [todos, setTodos] = useState(initialTodos);

  return (
    <List>
      {todos.map((todo) => (
        <ListItem
          key={todo.id}
          secondaryAction={<Checkbox checked={todo.completed} />}
        >
          <ListItemText primary={todo.title} />
        </ListItem>
      ))}
    </List>
  );
}
----

Wir brauchen noch einen Eventhandler:

----
  const handleChange = (index: number) => () => {
    const newTodos = [...todos];
    const changedTodo = newTodos[index];
    changedTodo.completed = !changedTodo.completed;
    setTodos(newTodos);
  };
----

----
            <Checkbox checked={todo.completed} onChange={handleChange(index)} />
----
